#include<iostream>
#include<cmath>
using namespace std;

int main(){
/*
int a[5];
cout<<"enter the number"<<endl;

for(int i=0;i<=4;i++)
{


    cin>>a[i];
}

cout<<"second data  ";
for(int i=0;i<=4;i++){
    cout<<a[i]<<"\t";
}
*/
/*
int a[5];
cout<<"enter the number"<<endl;

for(int i=0;i<=4;i++)
{
    cin>>a[i];
}

cout<<"second data  ";
for(int i=0;i<=4;i++){
            if(a[i]%2==0)

    cout<<a[i]<<"\t";




}

cout<<"second data  ";
for(int i=0;i<=4;i++){
            if(a[i]%2!=0)

    cout<<a[i]<<"\t";




}


cout<<"second data  ";
for(int i=4;i>=0;i--){


    cout<<a[i]<<"\t";



}
*/

int a[5]={8,2,3,1,6};
cout<<"enter the number"<<endl;

for(int i=0;i<=4;i++)
    if(i%2==0)


    cout<<a[i]<<"\t";




}






















